(function(){
'use strict';
let activeSponsor=null, detailData=null, packages=[];
const esc=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const money=v=>'$'+Number(v||0).toLocaleString();
const date=v=>{if(!v)return '—';try{return new Date(v).toLocaleDateString()}catch{return String(v)}};
const notify=m=>typeof toast==='function'?toast(m):alert(m);
const isLive=()=>typeof liveMode!=='undefined'&&liveMode&&typeof liveOrgId!=='undefined'&&liveOrgId;
const css=document.createElement('style');
css.textContent='.sponsor-row{cursor:pointer}.sponsor-row:hover td{background:#f3f6f1}.sd-hero{display:grid;grid-template-columns:1.1fr .9fr;gap:12px;margin-bottom:14px}.sd-summary{padding:16px;border-radius:17px;background:#173d2d;color:#fff}.sd-summary h4{font:800 22px Manrope;margin:4px 0}.sd-summary p{font-size:11px;color:#cbd9cf;margin:5px 0}.sd-kpis{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sd-kpi{padding:12px;border:1px solid var(--line);border-radius:14px;background:#fff}.sd-kpi small{color:var(--muted);font-size:10px}.sd-kpi b{display:block;font:800 17px Manrope;margin-top:3px}.sd-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:4px 0 12px}.sd-panel{display:none}.sd-panel.active{display:block}.sd-list{display:grid;gap:8px}.sd-card{border:1px solid var(--line);background:#fff;border-radius:13px;padding:11px}.sd-card strong{font-size:12px}.sd-card p{font-size:11px;color:var(--muted);line-height:1.45;margin:4px 0}.sd-progress{height:7px;border-radius:999px;background:#e5e9e3;overflow:hidden;margin-top:7px}.sd-progress i{display:block;height:100%;background:#617f69}.sd-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.sd-empty{padding:16px;text-align:center;color:var(--muted);font-size:11px;border:1px dashed var(--line);border-radius:13px}@media(max-width:760px){.sd-hero{grid-template-columns:1fr}}';
document.head.appendChild(css);
const modal=document.createElement('div');
modal.className='modal'; modal.id='sponsorDetailModal';
modal.innerHTML='<div class="modalbox" style="width:min(900px,100%)"><div class="modalhead"><h3 id="sdTitle">Sponsor relationship</h3><button class="x" id="sdClose" type="button">×</button></div><div id="sdBody"><div class="sd-empty">Loading…</div></div></div>';
document.body.appendChild(modal);
document.getElementById('sdClose').onclick=()=>modal.classList.remove('open');
modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
function demoData(s){const a=s.stage==='active';return{contacts:a?[{id:'dc',name:'Jordan Lee',title:'Community Partnerships',email:'jordan@example.com',primary_contact:true,notes:'Demo contact'}]:[],agreements:a?[{id:'da',name:(s.partner_level||'Annual')+' partnership',start_date:'2026-01-01',end_date:'2026-12-31',cash_value:s.cash_value||12000,in_kind_value:s.in_kind_value||6000,status:'active',package_name:s.partner_level||'Adventure Partner'}]:[],deliverables:a?[{id:'dd',agreement_id:'da',deliverable_type:'social',description:'Mission-focused partner features',quantity_committed:4,quantity_delivered:2,due_at:'2026-12-15',status:'in_progress'}]:[],outreach:[]}}
async function loadPackages(){if(!isLive()){packages=[{id:'pd',name:'Digital Partner',target_value:6000},{id:'pa',name:'Adventure Partner',target_value:18000},{id:'pm',name:'Mission Partner',target_value:36000}];return}const r=await sb.from('dh_sponsor_packages').select('id,name,target_value').eq('org_id',liveOrgId).eq('active',true).order('target_value');if(r.error)throw r.error;packages=r.data||[]}
async function loadDetails(s){if(!isLive())return demoData(s);const rs=await Promise.all([
sb.from('dh_sponsor_contacts').select('*').eq('org_id',liveOrgId).eq('sponsor_id',s.id).order('primary_contact',{ascending:false}),
sb.from('dh_sponsor_agreements').select('*,dh_sponsor_packages(name)').eq('org_id',liveOrgId).eq('sponsor_id',s.id).order('created_at',{ascending:false}),
sb.from('dh_sponsor_deliverables').select('*').eq('org_id',liveOrgId).eq('sponsor_id',s.id).order('created_at',{ascending:false}),
sb.from('dh_sponsor_outreach').select('*').eq('org_id',liveOrgId).eq('sponsor_id',s.id).order('created_at',{ascending:false})
]);const err=rs.find(x=>x.error)?.error;if(err)throw err;return{contacts:rs[0].data||[],agreements:(rs[1].data||[]).map(x=>({...x,package_name:x.dh_sponsor_packages?.name||''})),deliverables:rs[2].data||[],outreach:rs[3].data||[]}}
function tab(name){modal.querySelectorAll('.sd-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));modal.querySelectorAll('.sd-tabs .tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}
function render(){
const s=activeSponsor,d=detailData;const total=d.deliverables.reduce((n,x)=>n+Number(x.quantity_committed||0),0),done=d.deliverables.reduce((n,x)=>n+Number(x.quantity_delivered||0),0),pct=total?Math.round(done/total*100):0;
const pkg=packages.map(p=>'<option value="'+esc(p.name)+'" '+(s.partner_level===p.name?'selected':'')+'>'+esc(p.name)+'</option>').join('');
const agrOpts=['<option value="">Select agreement</option>'].concat(d.agreements.map(a=>'<option value="'+a.id+'">'+esc(a.name)+'</option>')).join('');
document.getElementById('sdTitle').textContent=s.name;
document.getElementById('sdBody').innerHTML=
'<div class="sd-hero"><div class="sd-summary"><span class="badge lime">'+esc(typeof stageLabel==='function'?stageLabel(s.stage):s.stage)+'</span><h4>'+esc(s.name)+'</h4><p>'+esc(s.cat||'Outdoor Partner')+(s.partner_level?' • '+esc(s.partner_level):'')+'</p><p>'+esc(s.notes||'No relationship notes yet.')+'</p></div><div class="sd-kpis"><div class="sd-kpi"><small>Opportunity</small><b>'+money(s.value)+'</b></div><div class="sd-kpi"><small>Fit</small><b>'+Number(s.fit||0)+'%</b></div><div class="sd-kpi"><small>Committed value</small><b>'+money(Number(s.cash_value||0)+Number(s.in_kind_value||0))+'</b></div><div class="sd-kpi"><small>Deliverables</small><b>'+pct+'%</b></div></div></div>'+
'<div class="sd-tabs"><button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="contacts">Contacts '+d.contacts.length+'</button><button class="tab" data-tab="agreements">Agreements '+d.agreements.length+'</button><button class="tab" data-tab="deliverables">Deliverables '+d.deliverables.length+'</button><button class="tab" data-tab="outreach">Outreach '+d.outreach.length+'</button></div>'+
'<div class="sd-panel active" data-panel="overview"><div class="formrow"><div class="field"><label>STAGE</label><select id="sdStage"><option value="prospect" '+(s.stage==='prospect'?'selected':'')+'>Prospect</option><option value="outreach" '+(s.stage==='outreach'?'selected':'')+'>Outreach</option><option value="active" '+(s.stage==='active'?'selected':'')+'>Active partner</option></select></div><div class="field"><label>PARTNER LEVEL</label><select id="sdLevel"><option value="">Unassigned</option>'+pkg+'</select></div></div><div class="field"><label>NEXT ACTION</label><input id="sdNext" value="'+esc(s.next||'')+'"></div><div class="field"><label>NOTES</label><textarea id="sdNotes">'+esc(s.notes||'')+'</textarea></div><div class="sd-actions"><button class="btn primary" id="sdSave">Save relationship</button></div></div>'+
'<div class="sd-panel" data-panel="contacts"><div class="sd-list">'+(d.contacts.length?d.contacts.map(c=>'<div class="sd-card"><strong>'+esc(c.name||'Unnamed')+(c.primary_contact?' ★':'')+'</strong><p>'+esc(c.title||'')+(c.email?' • '+esc(c.email):'')+(c.phone?' • '+esc(c.phone):'')+'</p></div>').join(''):'<div class="sd-empty">No contacts yet.</div>')+'</div><div class="reviewblock"><h4>Add contact</h4><div class="formrow"><div class="field"><label>NAME</label><input id="sdContactName"></div><div class="field"><label>TITLE</label><input id="sdContactTitle"></div></div><div class="formrow"><div class="field"><label>EMAIL</label><input id="sdContactEmail"></div><div class="field"><label>PHONE</label><input id="sdContactPhone"></div></div><label style="font-size:11px"><input type="checkbox" id="sdContactPrimary"> Primary contact</label><div class="sd-actions"><button class="btn primary" id="sdAddContact">Add contact</button></div></div></div>'+
'<div class="sd-panel" data-panel="agreements"><div class="sd-list">'+(d.agreements.length?d.agreements.map(a=>'<div class="sd-card"><strong>'+esc(a.name)+'</strong><p>'+esc(a.package_name||'Custom agreement')+' • '+date(a.start_date)+' to '+date(a.end_date)+' • '+esc(a.status)+'</p><p>Cash '+money(a.cash_value)+' • In-kind '+money(a.in_kind_value)+'</p></div>').join(''):'<div class="sd-empty">No agreements yet.</div>')+'</div><div class="reviewblock"><h4>Add agreement</h4><div class="field"><label>NAME</label><input id="sdAgrName" placeholder="2027 Annual Partnership"></div><div class="field"><label>PACKAGE</label><select id="sdAgrPackage"><option value="">No package</option>'+packages.map(p=>'<option value="'+p.id+'">'+esc(p.name)+' — '+money(p.target_value)+'</option>').join('')+'</select></div><div class="formrow"><div class="field"><label>START</label><input id="sdAgrStart" type="date"></div><div class="field"><label>END</label><input id="sdAgrEnd" type="date"></div></div><div class="formrow"><div class="field"><label>CASH VALUE</label><input id="sdAgrCash" type="number" value="0"></div><div class="field"><label>IN-KIND VALUE</label><input id="sdAgrKind" type="number" value="0"></div></div><div class="sd-actions"><button class="btn primary" id="sdAddAgr">Add agreement</button></div></div></div>'+
'<div class="sd-panel" data-panel="deliverables"><div class="sd-list">'+(d.deliverables.length?d.deliverables.map(x=>{const p=x.quantity_committed?Math.min(100,Math.round(Number(x.quantity_delivered||0)/Number(x.quantity_committed)*100)):0;return '<div class="sd-card"><strong>'+esc(x.description)+'</strong><p>'+esc(x.deliverable_type)+' • '+x.quantity_delivered+'/'+x.quantity_committed+' delivered • due '+date(x.due_at)+'</p><div class="sd-progress"><i style="width:'+p+'%"></i></div>'+(Number(x.quantity_delivered||0)<Number(x.quantity_committed||0)?'<div class="sd-actions"><button class="btn small sd-progress-btn" data-id="'+x.id+'" data-next="'+(Number(x.quantity_delivered||0)+1)+'">+ 1 delivered</button></div>':'')+'</div>'}).join(''):'<div class="sd-empty">No deliverables yet.</div>')+'</div><div class="reviewblock"><h4>Add deliverable</h4><div class="field"><label>AGREEMENT</label><select id="sdDelAgr">'+agrOpts+'</select></div><div class="formrow"><div class="field"><label>TYPE</label><select id="sdDelType"><option>social</option><option>video</option><option>event</option><option>report</option><option>logo placement</option><option>other</option></select></div><div class="field"><label>QUANTITY</label><input id="sdDelQty" type="number" min="1" value="1"></div></div><div class="field"><label>DESCRIPTION</label><input id="sdDelDesc"></div><div class="field"><label>DUE DATE</label><input id="sdDelDue" type="date"></div><div class="sd-actions"><button class="btn primary" id="sdAddDel">Add deliverable</button></div></div></div>'+
'<div class="sd-panel" data-panel="outreach"><div class="sd-list">'+(d.outreach.length?d.outreach.map(o=>'<div class="sd-card"><strong>'+esc(o.subject||'Sponsor outreach')+'</strong><p>'+esc(o.channel||'email')+' • '+esc(o.status)+' • '+date(o.created_at)+'</p><p>'+esc(o.body||'')+'</p></div>').join(''):'<div class="sd-empty">No outreach drafted yet.</div>')+'</div><div class="reviewblock"><h4>Draft outreach</h4><div class="field"><label>SUBJECT</label><input id="sdOutSubject" value="Dream Hunt partnership follow-up"></div><div class="field"><label>MESSAGE</label><textarea id="sdOutBody">Thank you for your interest in Dream Hunt Foundation. We would like to continue the conversation about a mission-aligned partnership that creates meaningful outdoor experiences and measurable partner value.</textarea></div><div class="sd-actions"><button class="btn primary" id="sdOutreach">Create approval draft</button></div><p style="font-size:10px;color:var(--muted)">Trial mode never sends sponsor outreach automatically.</p></div></div>';
modal.querySelectorAll('.sd-tabs .tab').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
document.getElementById('sdSave').onclick=saveOverview;document.getElementById('sdAddContact').onclick=addContact;document.getElementById('sdAddAgr').onclick=addAgreement;document.getElementById('sdAddDel').onclick=addDeliverable;document.getElementById('sdOutreach').onclick=createOutreach;modal.querySelectorAll('.sd-progress-btn').forEach(b=>b.onclick=()=>markProgress(b.dataset.id,Number(b.dataset.next)));
}
async function openSponsor(key){const list=typeof sponsors!=='undefined'?sponsors:[];let s=list.find(x=>String(x.id||x.name)===String(key));if(!s)return notify('Sponsor not found.');modal.classList.add('open');document.getElementById('sdTitle').textContent=s.name;document.getElementById('sdBody').innerHTML='<div class="sd-empty">Loading sponsor relationship…</div>';try{await loadPackages();if(isLive()){const r=await sb.from('dh_sponsors').select('*').eq('org_id',liveOrgId).eq('id',s.id).maybeSingle();if(r.error)throw r.error;if(r.data)s={...s,id:r.data.id,name:r.data.name,cat:r.data.category||s.cat,website:r.data.website||'',stage:r.data.stage||'prospect',partner_level:r.data.partner_level||'',value:Number(r.data.opportunity_value||0),cash_value:Number(r.data.cash_value||0),in_kind_value:Number(r.data.in_kind_value||0),fit:r.data.fit_score||0,next:r.data.next_action||'',notes:r.data.notes||''}}activeSponsor=s;detailData=await loadDetails(s);render()}catch(e){document.getElementById('sdBody').innerHTML='<div class="sd-empty">Could not load sponsor details: '+esc(e.message||e)+'</div>'}}
async function saveOverview(){const stage=document.getElementById('sdStage').value,partner_level=document.getElementById('sdLevel').value,next=document.getElementById('sdNext').value.trim(),notes=document.getElementById('sdNotes').value.trim();if(isLive()){const r=await sb.from('dh_sponsors').update({stage,partner_level:partner_level||null,next_action:next||null,notes:notes||null}).eq('org_id',liveOrgId).eq('id',activeSponsor.id);if(r.error)return notify(r.error.message)}Object.assign(activeSponsor,{stage,partner_level,next,notes});const i=sponsors.findIndex(x=>String(x.id||x.name)===String(activeSponsor.id||activeSponsor.name));if(i>=0)Object.assign(sponsors[i],activeSponsor);renderSponsors();render();notify('Sponsor relationship updated.')}
async function addContact(){const name=document.getElementById('sdContactName').value.trim();if(!name)return notify('Add a contact name.');const rec={id:'dc'+Date.now(),name,title:document.getElementById('sdContactTitle').value.trim(),email:document.getElementById('sdContactEmail').value.trim(),phone:document.getElementById('sdContactPhone').value.trim(),primary_contact:document.getElementById('sdContactPrimary').checked};if(isLive()){const r=await sb.from('dh_sponsor_contacts').insert({org_id:liveOrgId,sponsor_id:activeSponsor.id,name:rec.name,title:rec.title||null,email:rec.email||null,phone:rec.phone||null,primary_contact:rec.primary_contact,notes:null}).select().single();if(r.error)return notify(r.error.message);rec.id=r.data.id}detailData.contacts.unshift(rec);render();tab('contacts');notify('Sponsor contact added.')}
async function addAgreement(){const name=document.getElementById('sdAgrName').value.trim();if(!name)return notify('Add an agreement name.');const rec={id:'da'+Date.now(),name,package_id:document.getElementById('sdAgrPackage').value||null,start_date:document.getElementById('sdAgrStart').value||null,end_date:document.getElementById('sdAgrEnd').value||null,cash_value:Number(document.getElementById('sdAgrCash').value||0),in_kind_value:Number(document.getElementById('sdAgrKind').value||0),status:'active'};rec.package_name=packages.find(p=>p.id===rec.package_id)?.name||'';if(isLive()){const r=await sb.from('dh_sponsor_agreements').insert({org_id:liveOrgId,sponsor_id:activeSponsor.id,package_id:rec.package_id,name:rec.name,start_date:rec.start_date,end_date:rec.end_date,cash_value:rec.cash_value,in_kind_value:rec.in_kind_value,status:'active'}).select().single();if(r.error)return notify(r.error.message);rec.id=r.data.id}detailData.agreements.unshift(rec);render();tab('agreements');notify('Sponsor agreement added.')}
async function addDeliverable(){const agreement_id=document.getElementById('sdDelAgr').value;if(!agreement_id)return notify('Select an agreement first.');const description=document.getElementById('sdDelDesc').value.trim();if(!description)return notify('Add a deliverable description.');const rec={id:'dd'+Date.now(),agreement_id,deliverable_type:document.getElementById('sdDelType').value,description,quantity_committed:Number(document.getElementById('sdDelQty').value||1),quantity_delivered:0,due_at:document.getElementById('sdDelDue').value||null,status:'open'};if(isLive()){const r=await sb.from('dh_sponsor_deliverables').insert({org_id:liveOrgId,agreement_id,sponsor_id:activeSponsor.id,deliverable_type:rec.deliverable_type,description:rec.description,quantity_committed:rec.quantity_committed,quantity_delivered:0,due_at:rec.due_at?new Date(rec.due_at+'T12:00:00').toISOString():null,status:'open',proof:{}}).select().single();if(r.error)return notify(r.error.message);rec.id=r.data.id}detailData.deliverables.unshift(rec);render();tab('deliverables');notify('Sponsor deliverable added.')}
async function markProgress(id,qty){const x=detailData.deliverables.find(v=>String(v.id)===String(id));if(!x)return;const delivered=Math.min(Number(x.quantity_committed||0),qty),status=delivered>=Number(x.quantity_committed||0)?'completed':'in_progress';if(isLive()){const r=await sb.from('dh_sponsor_deliverables').update({quantity_delivered:delivered,status}).eq('org_id',liveOrgId).eq('id',id);if(r.error)return notify(r.error.message)}x.quantity_delivered=delivered;x.status=status;render();tab('deliverables');notify('Deliverable progress updated.')}
async function createOutreach(){const subject=document.getElementById('sdOutSubject').value.trim(),body=document.getElementById('sdOutBody').value.trim();if(!subject||!body)return notify('Add a subject and message.');const rec={id:'do'+Date.now(),channel:'email',subject,body,status:'draft',created_at:new Date().toISOString()};if(isLive()){const r=await sb.from('dh_sponsor_outreach').insert({org_id:liveOrgId,sponsor_id:activeSponsor.id,channel:'email',subject,body,status:'draft',created_by:liveUser.id}).select().single();if(r.error)return notify(r.error.message);rec.id=r.data.id;const q=await sb.from('dh_agent_actions').insert({org_id:liveOrgId,action_type:'sponsor_outreach',title:'Review outreach to '+activeSponsor.name,payload:{sponsor_id:activeSponsor.id,outreach_id:r.data.id,sponsor:activeSponsor.name,subject,body},risk_level:'medium',status:'queued',requires_human_approval:true});if(q.error)return notify('Draft saved, but queue failed: '+q.error.message);if(typeof loadAgentQueue==='function')await loadAgentQueue()}else if(typeof queue!=='undefined'){queue.unshift({id:'demo-out-'+Date.now(),icon:'↗',action_type:'sponsor_outreach',title:'Review outreach to '+activeSponsor.name,sub:'Sponsor outreach • draft ready',risk_level:'medium',status:'queued',payload:{sponsor:activeSponsor.name,subject,body}});if(typeof renderQueue==='function')renderQueue()}detailData.outreach.unshift(rec);render();tab('outreach');notify('Outreach draft queued for human approval.')}
function enhancedRenderSponsors(filter='all'){const data=(typeof sponsors!=='undefined'?sponsors:[]).filter(s=>filter==='all'||s.stage===filter),tbody=document.getElementById('sponsorRows');if(!tbody)return;tbody.innerHTML=data.map(s=>'<tr class="sponsor-row" data-sponsor-key="'+encodeURIComponent(String(s.id||s.name))+'"><td><div class="org">'+esc(s.name)+'</div><div class="sub">'+esc(s.cat||'Outdoor Partner')+'</div></td><td><span class="stage '+esc(s.stage)+'">'+esc(typeof stageLabel==='function'?stageLabel(s.stage):s.stage)+'</span></td><td class="value">'+money(s.value)+'</td><td>'+esc(s.next||'Qualify opportunity')+'</td><td><span class="badge '+(Number(s.fit||0)>=90?'lime':'')+'">'+Number(s.fit||0)+'%</span></td></tr>').join('');tbody.querySelectorAll('.sponsor-row').forEach(r=>r.onclick=()=>openSponsor(decodeURIComponent(r.dataset.sponsorKey)));const a=document.getElementById('activePartners');if(a)a.textContent=(typeof sponsors!=='undefined'?sponsors:[]).filter(s=>s.stage==='active').length}
if(typeof renderSponsors==='function'){renderSponsors=enhancedRenderSponsors;renderSponsors()}
window.openDreamHuntSponsor=openSponsor;
})();